### ISSUE TITLE
frontend compile error

### ISSUE THREAD

**Issue by eafun** [filecoin-project/filecoin-network-stats#24]
project: frontend
----------------------
npm install
----------------------
npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.2.7
npm WARN filecoin-network-stats-frontend@0.0.0 No description
npm WARN filecoin-network-stats-frontend@0.0.0 No repository field.

----------------------
npm run dev
----------------------
[0] multi (webpack)-dev-server/client?http://localhost:8081 (webpack)/hot/dev-server.js ./src/index.tsx 52 bytes {main} [built]
[./node_modules/c3/c3.css] 1020 bytes {main} [built]
[./node_modules/loglevel/lib/loglevel.js] 7.68 KiB {main} [built]
[./node_modules/normalize.css/normalize.css] 1.02 KiB {main} [built]
[./node_modules/react-dom/index.js] 1.33 KiB {main} [built]
[./node_modules/react-redux/es/index.js] 270 bytes {main} [built]
[./node_modules/react-router-dom/es/index.js] 1010 bytes {main} [built]
[./node_modules/react/index.js] 190 bytes {main} [built]
[./node_modules/strip-ansi/index.js] 161 bytes {main} [built]
[./node_modules/url/url.js] 22.8 KiB {main} [built]
[./node_modules/webpack-dev-server/client/index.js?http://localhost:8081] (webpack)-dev-server/client?http://localhost:8081 7.78 KiB {main} [built]
[./node_modules/webpack-dev-server/client/overlay.js] (webpack)-dev-server/client/overlay.js 3.58 KiB {main} [built]
[./node_modules/webpack-dev-server/client/socket.js] (webpack)-dev-server/client/socket.js 1.05 KiB {main} [built]
[./node_modules/webpack/hot/dev-server.js] (webpack)/hot/dev-server.js 1.61 KiB {main} [built]
[./src/index.tsx] 1020 bytes {main} [built]
    + 505 hidden modules

WARNING in EnvironmentPlugin - GA_TRACKING_ID environment variable is undefined.

You can pass an object with default values to suppress this warning.
See https://webpack.js.org/plugins/environment-plugin for example.

WARNING in EnvironmentPlugin - SENTRY_DSN environment variable is undefined.

You can pass an object with default values to suppress this warning.
See https://webpack.js.org/plugins/environment-plugin for example.

ERROR in ./src/ducks/overrides.ts
Module not found: Error: Can't resolve 'filecoin-network-stats-common/lib/domain/CategoryDatapoint' in '/file/data/wwwroot/filecoin/frontend/src/ducks'
 @ ./src/ducks/overrides.ts 50:26-95
 @ ./src/ducks/store.ts
 @ ./src/index.tsx
 @ multi (webpack)-dev-server/client?http://localhost:8081 (webpack)/hot/dev-server.js ./src/index.tsx

ERROR in ./src/components/DateSwitchingChart.tsx
Module not found: Error: Can't resolve 'filecoin-network-stats-common/lib/domain/ChartDuration' in '/file/data/wwwroot/filecoin/frontend/src/components'
 @ ./src/components/DateSwitchingChart.tsx 53:22-87
 @ ./src/components/storage/HistoricalUtilizationChart.tsx
 @ ./src/components/storage/StorageCostCapacity.tsx
 @ ./src/components/Main.tsx
 @ ./src/index.tsx
 @ multi (webpack)-dev-server/client?http://localhost:8081 (webpack)/hot/dev-server.js ./src/index.tsx

ERROR in ./src/ducks/stats.ts
Module not found: Error: Can't resolve 'filecoin-network-stats-common/lib/domain/Stats' in '/file/data/wwwroot/filecoin/frontend/src/ducks'
 @ ./src/ducks/stats.ts 50:14-71
 @ ./src/ducks/store.ts
 @ ./src/index.tsx
 @ multi (webpack)-dev-server/client?http://localhost:8081 (webpack)/hot/dev-server.js ./src/index.tsx

ERROR in ./src/ducks/overrides.ts
Module not found: Error: Can't resolve 'filecoin-network-stats-common/lib/domain/TimeseriesDatapoint' in '/file/data/wwwroot/filecoin/frontend/src/ducks'
 @ ./src/ducks/overrides.ts 49:28-99
 @ ./src/ducks/store.ts
 @ ./src/index.tsx
 @ multi (webpack)-dev-server/client?http://localhost:8081 (webpack)/hot/dev-server.js ./src/index.tsx

ERROR in [at-loader] ./src/ducks/stats.ts:4:47 
    TS2307: Cannot find module 'filecoin-network-stats-common/lib/domain/Stats'.

ERROR in [at-loader] ./src/ducks/overrides.ts:2:89 
    TS2307: Cannot find module 'filecoin-network-stats-common/lib/domain/TimeseriesDatapoint'.

ERROR in [at-loader] ./src/ducks/overrides.ts:3:83 
    TS2307: Cannot find module 'filecoin-network-stats-common/lib/domain/CategoryDatapoint'.

ERROR in [at-loader] ./src/ducks/overrides.ts:4:29 
    TS2307: Cannot find module 'filecoin-network-stats-common/lib/domain/ChartDuration'.

ERROR in [at-loader] ./src/components/MiningSummary.tsx:8:27 
    TS2307: Cannot find module 'filecoin-network-stats-common/lib/domain/Stats'.

ERROR in [at-loader] ./src/components/NodeMap.tsx:7:20 
    TS2307: Cannot find module 'filecoin-network-stats-common/lib/domain/Node'.

ERROR in [at-loader] ./src/components/TimelineDateChart.tsx:6:35 
    TS2307: Cannot find module 'filecoin-network-stats-common/lib/domain/TimeseriesDatapoint'.

ERROR in [at-loader] ./src/utils/averages.ts:2:36 
    TS2307: Cannot find module 'filecoin-network-stats-common/lib/domain/HistogramDatapoint'.

ERROR in [at-loader] ./src/utils/averages.ts:3:37 
    TS2307: Cannot find module 'filecoin-network-stats-common/lib/domain/TimeseriesDatapoint'.

ERROR in [at-loader] ./src/utils/timeseriesUnits.ts:1:35 
    TS2307: Cannot find module 'filecoin-network-stats-common/lib/domain/TimeseriesDatapoint'.

ERROR in [at-loader] ./src/components/storage/AverageStorageCostChart.tsx:3:35 
    TS2307: Cannot find module 'filecoin-network-stats-common/lib/domain/TimeseriesDatapoint'.

ERROR in [at-loader] ./src/components/GainLossTimelineChart.tsx:6:35 
    TS2307: Cannot find module 'filecoin-network-stats-common/lib/domain/TimeseriesDatapoint'.

ERROR in [at-loader] ./src/components/DateSwitchingChart.tsx:3:29 
    TS2307: Cannot find module 'filecoin-network-stats-common/lib/domain/ChartDuration'.

ERROR in [at-loader] ./src/components/SwitchableDateSwitchingChart.tsx:6:29 
    TS2307: Cannot find module 'filecoin-network-stats-common/lib/domain/ChartDuration'.

ERROR in [at-loader] ./src/components/Home.tsx:9:41 
    TS2307: Cannot find module 'filecoin-network-stats-common/lib/domain/Stats'.

ERROR in [at-loader] ./src/components/Home.tsx:25:29 
    TS2307: Cannot find module 'filecoin-network-stats-common/lib/domain/ChartDuration'.

ERROR in [at-loader] ./src/components/Retrieval.tsx:8:35 
    TS2307: Cannot find module 'filecoin-network-stats-common/lib/domain/TimeseriesDatapoint'.

ERROR in [at-loader] ./src/components/HistogramChart.tsx:2:34 
    TS2307: Cannot find module 'filecoin-network-stats-common/lib/domain/HistogramDatapoint'.

ERROR in [at-loader] ./src/components/HistogramChart.tsx:48:17 
    TS2339: Property 'count' does not exist on type 'AugmentedHistogramDatapoint'.

ERROR in [at-loader] ./src/components/HistogramChart.tsx:49:21 
    TS2339: Property 'count' does not exist on type 'AugmentedHistogramDatapoint'.

ERROR in [at-loader] ./src/components/HistogramChart.tsx:54:17 
    TS2339: Property 'count' does not exist on type 'AugmentedHistogramDatapoint'.

ERROR in [at-loader] ./src/components/token/TokenHoldingsDistribution.tsx:2:34 
    TS2307: Cannot find module 'filecoin-network-stats-common/lib/domain/HistogramDatapoint'.

ERROR in [at-loader] ./src/components/token/HistoricalCollateralChart.tsx:2:35 
    TS2307: Cannot find module 'filecoin-network-stats-common/lib/domain/TimeseriesDatapoint'.

ERROR in [at-loader] ./src/components/token/HistoricalCollateralChart.tsx:3:29 
    TS2307: Cannot find module 'filecoin-network-stats-common/lib/domain/ChartDuration'.

ERROR in [at-loader] ./src/components/token/HistoricalBlockRewards.tsx:2:35 
    TS2307: Cannot find module 'filecoin-network-stats-common/lib/domain/TimeseriesDatapoint'.

ERROR in [at-loader] ./src/components/token/HistoricalBlockRewards.tsx:3:29 
    TS2307: Cannot find module 'filecoin-network-stats-common/lib/domain/ChartDuration'.

ERROR in [at-loader] ./src/components/StackedColumnChart.tsx:2:33 
    TS2307: Cannot find module 'filecoin-network-stats-common/lib/domain/CategoryDatapoint'.

ERROR in [at-loader] ./src/components/token/CoinsInCirculation.tsx:2:33 
    TS2307: Cannot find module 'filecoin-network-stats-common/lib/domain/CategoryDatapoint'.

ERROR in [at-loader] ./src/components/token/CoinsInCirculation.tsx:3:29 
    TS2307: Cannot find module 'filecoin-network-stats-common/lib/domain/ChartDuration'.

ERROR in [at-loader] ./src/components/token/BlockRewardLifecycle.tsx:2:35 
    TS2307: Cannot find module 'filecoin-network-stats-common/lib/domain/TimeseriesDatapoint'.

ERROR in [at-loader] ./src/components/storage/MinerCountChart.tsx:2:35 
    TS2307: Cannot find module 'filecoin-network-stats-common/lib/domain/TimeseriesDatapoint'.

ERROR in [at-loader] ./src/components/storage/MinerCountChart.tsx:3:29 
    TS2307: Cannot find module 'filecoin-network-stats-common/lib/domain/ChartDuration'.

ERROR in [at-loader] ./src/components/storage/StorageMinersTable.tsx:5:25 
    TS2307: Cannot find module 'filecoin-network-stats-common/lib/domain/MinerStat'.

ERROR in [at-loader] ./src/components/PercentageLineChart.tsx:2:33 
    TS2307: Cannot find module 'filecoin-network-stats-common/lib/domain/CategoryDatapoint'.

ERROR in [at-loader] ./src/components/storage/MiningEvolutionChart.tsx:5:33 
    TS2307: Cannot find module 'filecoin-network-stats-common/lib/domain/CategoryDatapoint'.

ERROR in [at-loader] ./src/utils/randomData.ts:2:35 
    TS2307: Cannot find module 'filecoin-network-stats-common/lib/domain/TimeseriesDatapoint'.

ERROR in [at-loader] ./src/utils/randomData.ts:3:33 
    TS2307: Cannot find module 'filecoin-network-stats-common/lib/domain/CategoryDatapoint'.

ERROR in [at-loader] ./src/components/storage/StorageDeals.tsx:7:34 
    TS2307: Cannot find module 'filecoin-network-stats-common/lib/domain/HistogramDatapoint'.

ERROR in [at-loader] ./src/components/storage/StorageCapacityHistogram.tsx:2:34 
    TS2307: Cannot find module 'filecoin-network-stats-common/lib/domain/HistogramDatapoint'.

ERROR in [at-loader] ./src/components/storage/HistoricalCollateralPerGBChart.tsx:2:35 
    TS2307: Cannot find module 'filecoin-network-stats-common/lib/domain/TimeseriesDatapoint'.

ERROR in [at-loader] ./src/components/storage/HistoricalCollateralPerGBChart.tsx:3:29 
    TS2307: Cannot find module 'filecoin-network-stats-common/lib/domain/ChartDuration'.

ERROR in [at-loader] ./src/components/storage/StorageCostCapacityBySizeBreakdown.tsx:2:40 
    TS2307: Cannot find module 'filecoin-network-stats-common/lib/domain/CostCapacityForMinerStat'.

ERROR in [at-loader] ./src/components/storage/HistoricalStoragePriceChart.tsx:2:35 
    TS2307: Cannot find module 'filecoin-network-stats-common/lib/domain/TimeseriesDatapoint'.

ERROR in [at-loader] ./src/components/storage/HistoricalStoragePriceChart.tsx:3:29 
    TS2307: Cannot find module 'filecoin-network-stats-common/lib/domain/ChartDuration'.

ERROR in [at-loader] ./src/components/storage/HistoricalUtilizationChart.tsx:2:35 
    TS2307: Cannot find module 'filecoin-network-stats-common/lib/domain/TimeseriesDatapoint'.

ERROR in [at-loader] ./src/components/storage/HistoricalUtilizationChart.tsx:3:29 
    TS2307: Cannot find module 'filecoin-network-stats-common/lib/domain/ChartDuration'.
Child html-webpack-plugin for "index.html":
     1 asset
    Entrypoint undefined = index.html
    [./node_modules/html-webpack-plugin/lib/loader.js!./src/index.html] 2.7 KiB {0} [built]
    [./node_modules/lodash/lodash.js] 527 KiB {0} [built]
    [./node_modules/webpack/buildin/global.js] (webpack)/buildin/global.js 472 bytes {0} [built]
    [./node_modules/webpack/buildin/module.js] (webpack)/buildin/module.js 497 bytes {0} [built]
ℹ ｢wdm｣: Failed to compile.

**Comment by mslipper** [comment]
Hey there! Did you run `npm run build` from the `common` directory prior to running `npm install` in the `frontend` directory? These errors imply that the common libraries were never build.

**Comment by eafun** [comment]
> Hey there! Did you run `npm run build` from the `common` directory prior to running `npm install` in the `frontend` directory? These errors imply that the common libraries were never build.

yes,thank u~
