### ISSUE TITLE
can not collect statistics on node

### ISSUE THREAD

**Issue by yangjian102621** [filecoin-project/filecoin-network-stats#27]
I am not sure if it is wrong with my configuration. 
I did it according to the READM.md

```bash
go-filecoin config heartbeat.nickname '"Pizzanode"'
go-filecoin config heartbeat.beatTarget "/dns4/<your-backend-domain-name>/tcp/8080/ipfs/<your-peer-id>"
```
i replace the `<your-backend-domain-name>` to `127.0.0.1` and replace the `<your-peer-id>` to the Peer ID of the `FULL_NODE`.

Well, i got an error in `go-filecoin deamon` after configured the `heartbeat.beatTarget`

```
11:24:07.005 DEBUG    metrics: Heartbeat service failed to connect for 16m49.995175956s: protocol not supported heartbeat.go:148
11:24:17.004 DEBUG    metrics: Heartbeat service attempting to connect, targetAddress: /dns4/127.0.0.1/tcp/8080/ipfs/QmbUAMCS9bknw5tG4BTpDRsGxFSnvbCqgA6uo8Hvx1wcHc heartbeat.go:213
11:24:17.005 DEBUG    metrics: failed to open stream, peerID: <peer.ID Qm*x1wcHc>, targetAddr: /dns4/127.0.0.1/tcp/8080 protocol not supported heartbeat.
```

here is my `.env` 

```
export DB_URL=postgresql://test:test111@localhost:5432
export FULL_NODE_URL=http://127.0.0.1:3453
export IS_MASTER=true
export PEER_INFO_FILE=./peerId.json
export HEARTBEAT_PORT=8080
export API_PORT=8081
export LOG_LEVEL=silly
```

**Comment by mslipper** [comment]
Hi there,

The `beatTarget` is specifying `dns4`, which requires a domain name. Change it to `/ip4/127.0.0.1/tcp/8080/ipfs/QmbUAMCS9bknw5tG4BTpDRsGxFSnvbCqgA6uo8Hvx1wcHc` and it should work.

**Comment by mslipper** [comment]
Also, the peer ID needs to be the peer ID of the _dashboard server_, not the full node.

**Comment by yangjian102621** [comment]
@mslipper 
I modify the `beatTarget` as you suggestion and  it works.

Thanks.
