### ISSUE TITLE
[bug]There is a problem with the mining data displayed on the Devnet website.

### ISSUE THREAD

**Issue by frrist** [filecoin-project/filecoin-network-stats#30]
@zhengboowen commented on [Wed May 29 2019](https://github.com/filecoin-project/go-filecoin/issues/2849)

The mining data on Filecoin devnet seems to have a problem. These data are displayed two days ago. Did the network not update the blockchain data in time? Or is there a problem with the blockchain data ?

![20190529 web data](https://user-images.githubusercontent.com/51158073/58550629-c1a75e80-8240-11e9-88c0-3c422bf3c309.jpeg)

**Comment by frrist** [comment]
Hey @zhengboowen, thanks for filing. I have moved the issue to this repo as this is a bug with the filecoin-network-stats dashboard and not go-filecoin itself. @mslipper will be taking this over and you can track progress of a fix here.

**Comment by mslipper** [comment]
This is now fixed.
