### ISSUE TITLE
Duplicate declarations of node.process and NodeJS.Process

### ISSUE THREAD

**Issue by eshon** [filecoin-project/filecoin-network-stats#31]
Just an FYI - from a fresh checkout I was getting the compile error below because there are 2 conflicting declarations of `declare var process`, one from `node_modules/@types/node` and one from `frontend/types/index.d.ts`. 

Commented out the one in `node_modules/@types/node/globals.d.ts` and the error goes away. Compiles fine now.

```
Failed to compile.

[at-loader] ./node_modules/@types/node/globals.d.ts:162:13 
    TS2403: Subsequent variable declarations must have the same type.  Variable 'process' must be of type '{ env: { BACKEND_URL: string; SENTRY_DSN?: string; GA_TRACKING_ID?: string; }; }', but here has type 'Process'.
```

```
> npm ls @types/node
filecoin-network-stats/frontend
└─┬ webpack-dev-server@3.5.0
  └─┬ del@4.1.1
    └─┬ @types/glob@7.1.1
      └── @types/node@12.0.4
```

**Comment by mslipper** [comment]
Ah, interesting - are you using Yarn or NPM for your package management? Odd that it doesn't appear on the build machine.

**Comment by eshon** [comment]
npm

 🐾
