### ISSUE TITLE
Check genesisCID in heartbeat for network filtering

### ISSUE THREAD

**Issue by mishmosh** [filecoin-project/filecoin-network-stats#33]
Currently the dashboard counts *any* node that connects to it, regardless of network or version. The result is an misleading count of participating nodes.

Let’s check genesisCID in heartbeat messages (will have to be added via https://github.com/filecoin-project/go-filecoin/issues/2982). Then the stats dashboard could reject connections from nodes that are no longer on the correct network.

Based on chat discussion w/ @mslipper @frrist.

**Comment by eshon** [comment]
Merged via #42
