### ISSUE TITLE
Apply block datastructure changes

### ISSUE THREAD

**Issue by mishmosh** [filecoin-project/filecoin-network-stats#45]
This is a placeholder issue for necessary updates due to changes to block datastructure in https://github.com/filecoin-project/go-filecoin/pull/3185.

**Comment by ZenGround0** [comment]
The major breaking change is that messages are no longer part of the block object returned from `show block`.  We can use either `dag get` or make a new `show messages | receipts` to get this data.

**Comment by mishmosh** [comment]
@ZenGround0 plans to fix by end of week. Please correct if plans change.

**Comment by eshon** [comment]
Fixed by #50 and #51
