### ISSUE TITLE
Improve build process and instructions

### ISSUE THREAD

**Issue by ZenGround0** [filecoin-project/filecoin-network-stats#47]
Installing and building for local development needs improvement.  There should be some instructions on running postgres and making it clear that it is required to build from the common directory for the backend to build.  

There should be a single command that builds everything and another that starts everything other than the data base and the filecoin node.

**Comment by ZenGround0** [comment]
`npm install db-migrate` is a hidden installation dependency

**Comment by ZenGround0** [comment]
`db-migrate` does not work by default.  Can't find database.json configuration file

**Comment by eshon** [comment]
This has been fixed
